### ISSUE TITLE
运行提示链接错误，是不是缺少静态库？

### ISSUE THREAD

**Issue by smeron** [halohily/LYSSPai#3]

**Comment by halohily** [comment]
提供一下提示信息吧

**Comment by smeron** [comment]
![snip20170920_31](https://user-images.githubusercontent.com/13427454/30625366-5fce1d4c-9df5-11e7-8d91-01ed96b4d786.png)

**Comment by smeron** [comment]
![snip20170920_32](https://user-images.githubusercontent.com/13427454/30630318-ae9e0e2e-9e12-11e7-89e4-86494d3fb9dd.png)
